export const SRI_LANKA_TRIBES_QA = [
  {
    key: "visa",
    title: "Do I need a visa to visit Sri Lanka?",
    body: "What visa or Electronic Travel Authorization do I need before visiting Sri Lanka, and how long does it normally allow me to stay?",
    answer: "Most nationalities need an Electronic Travel Authorization (ETA) before arriving — a short online form usually approved within 24–48 hours. Depending on your nationality it's free or paid, and covers a double-entry stay of up to 30 days, extendable by up to 90 more days from the Department of Immigration in Colombo. Apply only through the official ETA portal — third-party sites charge more for the same thing.",
    tags: ["visa", "eta", "entry", "immigration"],
  },
  {
    key: "best-time",
    title: "When's the best time to visit Sri Lanka?",
    body: "How do Sri Lanka's two monsoon seasons affect the best time to visit different parts of the island?",
    answer: "Sri Lanka has two monsoons that hit opposite coasts at different times, so it's less about a \"good month\" and more about picking the right region. The south and west coasts (Colombo, Galle, Bentota) are driest December–April; the north and east (Trincomalee, Jaffna) are best May–September. If you're unsure, April, May, and September are quieter shoulder months with decent weather almost everywhere.",
    tags: ["weather", "monsoon", "season", "climate"],
  },
  {
    key: "currency",
    title: "What currency should I use, and do cards work?",
    body: "Should I bring cash or use cards in Sri Lanka, and where can I get Sri Lankan Rupees after arriving?",
    answer: "Sri Lanka uses the Rupee (LKR) — you can't get it before you land, so exchange cash or use an ATM on arrival. Cards are widely accepted in hotels, restaurants, and shops in cities and tourist areas, but tuk-tuks, local eateries, and rural guesthouses are cash-only. Carry enough rupees before heading off the beaten path, and tell your bank you're traveling so your card doesn't get blocked.",
    tags: ["currency", "rupee", "lkr", "cash", "cards"],
  },
  {
    key: "safety",
    title: "Is Sri Lanka safe for solo and female travelers?",
    body: "What safety issues should solo travelers, including women traveling alone, be aware of in Sri Lanka?",
    answer: "Violent crime against tourists is rare, and Sri Lanka is generally a manageable solo destination, including for women traveling alone. Most issues are practical rather than dangerous, such as overcharging, unlicensed taxis, or unwanted attention. Normal travel vigilance still applies: use reputable transport and accommodation, keep others informed of your plans, and trust your instincts.",
    tags: ["safety", "solo-travel", "female-travel", "security"],
  },
  {
    key: "transport",
    title: "How do I get around Sri Lanka?",
    body: "When should I use trains, buses, tuk-tuks, or a hired car and driver to travel around Sri Lanka?",
    answer: "Trains, buses, tuk-tuks, and hired cars with drivers are all common. Trains are the scenic, budget option; a car and driver is the easiest way to cover ground comfortably; and tuk-tuks work well for short local trips. Check current permit requirements before arranging any self-drive tuk-tuk rental.",
    tags: ["transport", "train", "tuk-tuk", "bus", "driver"],
  },
  {
    key: "sim",
    title: "Do I need a local SIM card in Sri Lanka?",
    body: "Is an eSIM or airport tourist SIM the better option for mobile data while traveling around Sri Lanka?",
    answer: "Most travelers get an eSIM before arrival or pick up a tourist SIM at the airport. Dialog, Mobitel, and Hutch operate arrivals-hall counters and normally require your passport. Packages and prices change, so compare the current data allowances and coverage before buying.",
    tags: ["sim-card", "esim", "internet", "data"],
  },
  {
    key: "tipping",
    title: "Is tipping expected in Sri Lanka?",
    body: "When is it appropriate to tip at restaurants, hotels, or for drivers and guides in Sri Lanka?",
    answer: "Tipping is appreciated but not obligatory. Check your bill first because many hotels and restaurants already add a service charge. Where it is not included, rounding up or tipping around 10% for good service is common. Drivers and guides are usually tipped per day rather than per ride.",
    tags: ["tipping", "service-charge", "etiquette"],
  },
  {
    key: "temple-dress",
    title: "What should I wear when visiting temples?",
    body: "What clothing and photography etiquette should visitors follow at Buddhist and Hindu temples in Sri Lanka?",
    answer: "Cover your shoulders and knees, and remove shoes and any hat before entering. Beachwear and tight or sheer clothing are not appropriate at Buddhist or Hindu sites. Loose, breathable clothing works well in the heat while keeping you covered, and you should always ask before photographing statues or monks.",
    tags: ["temple", "dress-code", "etiquette", "clothing"],
  },
  {
    key: "water",
    title: "Can I drink the tap water in Sri Lanka?",
    body: "Is tap water safe for visitors, and should I also be careful about ice at restaurants and street stalls?",
    answer: "Visitors should generally use bottled or properly filtered water. Water quality varies, and travelers may not be accustomed to local conditions. At smaller restaurants or street stalls, ask whether ice is made from filtered water if you are unsure.",
    tags: ["tap-water", "drinking-water", "food-safety"],
  },
  {
    key: "vaccinations",
    title: "Do I need vaccinations before visiting Sri Lanka?",
    body: "Which vaccinations or health precautions should I discuss with a travel clinic before visiting Sri Lanka?",
    answer: "Requirements and recommendations depend on where you are traveling from and your personal health history. Yellow Fever documentation may be required when arriving from a risk country, while hepatitis A and typhoid are commonly discussed for travelers. Check current official guidance and speak to a travel clinic several weeks before departure.",
    tags: ["vaccination", "health", "travel-clinic"],
  },
  {
    key: "budget",
    title: "How much should I budget per day in Sri Lanka?",
    body: "What daily budget should I plan for accommodation, food, transport, and major attractions in Sri Lanka?",
    answer: "Costs vary significantly by travel style. Budget travelers using public transport, local food, and simple accommodation spend much less than travelers hiring private drivers or staying in higher-end hotels. Major attractions often charge separate foreign-visitor entrance fees, so check current prices and budget those in addition to daily expenses.",
    tags: ["budget", "cost", "daily-spend", "prices"],
  },
  {
    key: "language",
    title: "Will English get me by in Sri Lanka?",
    body: "Which languages are spoken in Sri Lanka, and how widely is English understood outside tourist areas?",
    answer: "Sinhala and Tamil are the official languages, while English is widely used in hotels, restaurants, and tourist areas. English may be less common in rural villages and local markets, where learning a few basic Sinhala or Tamil phrases can be helpful and appreciated.",
    tags: ["language", "sinhala", "tamil", "english"],
  },
  {
    key: "trip-length",
    title: "How many days do I need to see Sri Lanka?",
    body: "How long should I allow for Sri Lanka if I want to visit the ancient cities, hill country, and coast without rushing?",
    answer: "A week can cover selected highlights if you keep the route focused. Ten to fourteen days gives you more time for the ancient cities, hill country, and coast without rushing. With five days or less, concentrate on one or two nearby regions rather than trying to circle the island.",
    tags: ["itinerary", "trip-length", "planning"],
  },
  {
    key: "plug",
    title: "What plug adapter do I need in Sri Lanka?",
    body: "Which socket types and voltage should I prepare for when bringing electronics to Sri Lanka?",
    answer: "Sri Lanka uses 230V electricity and commonly has UK-style type G sockets. Types D and M can also appear, especially in older buildings. A universal travel adapter is the safest option, and you should confirm that your devices support 230V.",
    tags: ["plug", "adapter", "electricity", "voltage"],
  },
  {
    key: "meet-travelers",
    title: "What's the easiest way to meet other travelers in Sri Lanka?",
    body: "How can I find other travelers going to the same Sri Lankan destinations and coordinate a trip together?",
    answer: "Use HiBowan to post the trip you are planning or browse trips that are already forming, then connect with fellow travelers heading the same way. HiBowan does not handle bookings or payments, so travelers coordinate the practical details themselves after connecting.",
    tags: ["meet-travelers", "hibowan", "travel-companions"],
  },
] as const;